---
- name: Add an apt's signing key
  apt_key:
    url: https://www.mongodb.org/static/pgp/server-4.2.asc
    state: present
  tags: install

- name: Add specified repository into sources list
  apt_repository:
    repo: deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
    state: present
    update_cache: true
  tags: install

- name: Install MongoDB
  apt:
    name: mongodb-org
    state: present
    allow_unauthenticated: true
  notify:
    - Replace MongoDB's socket
    - reload mongod
  tags: install

- name: Enable MongoDB
  systemd: name=mongod enabled=yes
  tags: install
